name: 编译浏览器

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 准备开始
      uses: actions/checkout@v3
      
    - name: 设置JAVA环境
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: 建立工作目录
      run: |
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: 克隆源码
      working-directory: /workdir
      run: |
        git clone https://github.com/Slion/Fulguris -b main browser
        ln -sf /workdir/browser $GITHUB_WORKSPACE/browser
        cd browser
        wget https://gist.github.com/wangshe/ef25a5309766a5d9c3da7bdb1a7553e1/raw/browser.patch
        git apply browser.patch
        cd app/src/main/assets
        rm -rf ask.png ask.webp brave.webp duckduckgo.png duckduckgo.webp ecosia.webp ekoru.webp mojeek.webp naver.png naver.webp qwant.webp searx.webp startpage.png startpage.webp yahoo.png yahoo.webp yandex.png yandex.webp

    - name: 开始编译
      run: |
        cd browser
        chmod +x gradlew
        ./gradlew assembleStyxBaseUndef

    - name: 上传apk
      uses: actions/upload-artifact@main
      with:
        name: browser
        path: browser/app/build/outputs/apk
