name: 编译浏览器

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: 设置权限
      run: chmod +x gradlew
      
    - name: 打补丁
      run: |
        wget https://gist.github.com/wangshe/ef25a5309766a5d9c3da7bdb1a7553e1/raw/browser.patch
        git apply browser.patch
        
    - name: 开始编译
      run: ./gradlew assembleStyxBaseUndef

    - name: 上传build目录
      uses: actions/upload-artifact@main
      with:
        name: browser
        path: app/build
